export const isEnglish = () => typeof window !== "undefined" && window.location.pathname.startsWith("/en/");
const copy: Record<string,string> = {
  "هل الأسعار على المنصة نهائية وموثقة؟":"Are the listed prices verified and final?",
  "كل وحدة عندنا جاية مباشرة من الشركة المطوّرة — السعر والمساحة وخطة السداد بيتم تحديثهم من المصدر. مفيش إعلانات مكررة ولا أسعار وهمية زي مواقع الإعلانات المفتوحة.":"Our properties come directly from developers. Prices, sizes and payment plans are updated from the source, without the duplicate listings and misleading prices found on open listing sites.",
  "هل بتاخدوا عمولة مني كمشتري؟":"Do you charge buyers a commission?",
  "لا. احنا بنتعامل مباشرة مع المطورين، والسعر اللي بتشوفه هو سعر المطور الرسمي من غير أي زيادة. اتفاقك النهائي بيتم مع المطور نفسه.":"No. We work directly with developers and show their official prices without a markup. Your final agreement is with the developer.",
  "إزاي يشتغل البحث بالذكاء الاصطناعي؟":"How does AI property search work?",
  "بتكتب أو بتتكلم بالطريقة اللي تحبها — «عايز شاليه في الساحل تحت ٩ مليون» مثلًا — والمساعد بيفهم الموقع والميزانية ونوع الوحدة ويرجعلك بنتائج مطابقة من مخزون موثق، ويكمل معاك على واتساب بالتفاصيل.":"Type or speak naturally, for example ‘a North Coast chalet under EGP 9 million’. The assistant identifies your area, budget and property type to find inventory matches. You can continue your enquiry on WhatsApp.",
  "أقدر أشتري بمقدم كام؟":"What down payment do I need?",
  "معظم المشاريع عندنا بتبدأ بمقدم ٥-١٠٪ وتقسيط من ٥ لحد ١٠ سنين. استخدم حاسبة الأقساط عشان تشوف القسط الشهري التقريبي لأي سعر.":"Most listed projects start with a 5–10% down payment and payment terms of 5–10 years. Use the calculator to estimate a monthly payment for your chosen price.",
  "هل الوحدات دي ريسيل ولا من المطور مباشرة؟":"Are these resale or developer-direct properties?",
  "كل الوحدات على المنصة من المطور مباشرة (أول مالك). ده بيضمنلك أحسن سعر، عقد رسمي من الشركة، وخطة سداد كاملة من غير أوفر.":"The platform lists developer-direct properties for first owners, with an official developer contract and payment plan, without a resale premium.",
  "بحث صوتي وذكي بالعربي والإنجليزي":"Smart voice search in Arabic and English",
  "وحدات موثقة من المطور مباشرة":"Verified, developer-direct properties",
  "مرافقة كاملة لحد التعاقد":"Guidance through to signing",
  "مين إحنا؟":"Who we are",
  "مش موقع إعلانات.":"More than a listing site.",
  "مساعد شراء عقاري.":"Your property buying assistant.",
  "تايكونز اتعملت عشان تحل المشكلة اللي كلنا عدينا بيها: آلاف الإعلانات المكررة، سماسرة بأسعار وهمية، وساعات ضايعة في المكالمات. إحنا بنجمع الوحدات من المطوّر مباشرة، ونخليك توصف اللي عايزه بجملة واحدة — والمساعد يوصّلك للوحدة الصح.":"Tycoons was created to cut through duplicate listings, misleading prices and hours of phone calls. We bring together developer-direct properties: describe what you need in one sentence, and our assistant helps you find the right match.",
  "اعرف أكتر عن تايكونز":"Discover Tycoons",
  "كمباوند فاخر في القاهرة الجديدة":"A premium residential community in New Cairo",
  "سنة التأسيس":"Founded",
  "وحدة متاحة بآخر مراجعة":"Available homes at the latest review",
  "خطّط قبل ما تسأل":"Plan with confidence",
  "حاسبة الأقساط":"Payment calculator",
  "اعرف القسط الشهري التقريبي قبل ما تكلّم أي حد — حرّك المؤشرات وشوف النتيجة لحظيًا.":"Estimate your monthly payment before you enquire. Adjust the sliders and see the result instantly.",
  "القسط الشهري التقريبي":"Estimated monthly payment",
  "ج.م":"EGP",
  "قيمة المقدم":"Down payment amount",
  "اسأل عن خطة السداد على واتساب":"Ask about the payment plan on WhatsApp",
  "جرّب بنفسك":"Explore your options",
  "سعر الوحدة":"Property price",
  "المقدم":"Down payment",
  "مدة التقسيط":"Payment term",
  "شركاء موثوقون":"Trusted partners",
  "مطوّرون موثوقون":"Trusted developers",
  "كل الوحدات مباشرة من المطوّر — بيانات وأسعار موثّقة، من غير وسطاء وهميين.":"Developer-direct properties with verified information and prices, without misleading intermediaries.",
  "استكشف كل المطورين ومشاريعهم":"Explore all developers and their projects",
  "عندك سؤال؟":"Questions?",
  "الأسئلة الشائعة":"Frequently asked questions",
  "كل اللي محتاج تعرفه عن الشراء من المطور مباشرة والبحث بالذكاء الاصطناعي.":"What you need to know about buying developer-direct and searching with AI.",
  "شوف كل الأسئلة الشائعة":"View all frequently asked questions",
  "عقارك الجاي يبدأ بجملة واحدة":"Your next property starts with one sentence",
  "ابحث بالذكاء الاصطناعي والصوت — من المطوّرين مباشرة، من غير وسطاء.":"Search with AI and voice for developer-direct properties.",
  "ابدأ البحث":"Start searching",
  "كلمنا واتساب":"Chat on WhatsApp",
  "يدعم البحث الصوتي بالعربي والإنجليزي":"Voice search in Arabic and English",
  "ابحث عن عقارك بالذكاء الاصطناعي والصوت — من المطوّرين مباشرة.":"Find your property with AI and voice, directly from developers.",
  "المنصة":"Explore",
  "دليل المشاريع":"Project directory",
  "من نحن":"About us",
  "الحاسبة":"Calculator",
  "المناطق":"Areas",
  "منهجية البيانات":"Data methodology",
  "سياسة التصحيح":"Corrections policy",
  "تواصل معنا":"Contact us",
  "الخصوصية والمحادثات الصوتية":"Privacy and voice conversations",
  "المساعد الصوتي يعمل بالذكاء الاصطناعي. يُستخدم صوتك لمعالجة طلبك والرد عليك، وقد يخطئ في فهم الكلام؛ يُرجى تأكيد الأرقام والتفاصيل المهمة. عدم حفظ تسجيل لدينا لا يعني عدم معالجة الصوت لدى مزوّد الخدمة.":"Our voice assistant uses AI. Your voice is processed to understand and answer your request. Speech recognition can make mistakes; please confirm important numbers and details. Not saving a recording with us does not mean the service provider does not process your audio.",
  "أثناء المحادثة يُجهّز تسجيل صوتي ونص مؤقتان على جهازك. بعد إنهائها يمكنك مراجعة بيانات التواصل ونص الطلب ثم تأكيد إرسالهما للفريق، وإرفاق الصوت اختياريًا. إغلاق النموذج دون إرسال لا يرفع هذه البيانات إلى لوحة المبيعات. قد لا يكتمل التسجيل عند إغلاق الصفحة أو انقطاع الاتصال.":"During the conversation, temporary audio and text are prepared on your device. Afterwards you can review and submit your contact details and conversation text, optionally attaching audio. Closing the form without submitting does not upload these details to our sales dashboard. Closing the page or losing connection can leave the recording incomplete.",
  "الغرض من الحفظ هو متابعة طلبك ومراجعة جودة الخدمة، مع ربط التسجيل وملخص الاحتياجات بملف العميل. تُحفظ التسجيلات في مساحة خاصة على Supabase، ويقتصر الوصول على صاحب الحساب والموظف المسؤول بعد ربط الطلب بكارت العميل، عبر روابط مؤقتة. تتوقف إتاحة تشغيل الصوت بعد 30 يومًا؛ الحذف الدائم يتم بالمراجعة أو بطلب منك، وليس تلقائيًا حاليًا.":"Saved conversations help us follow up on your request and review service quality. Audio is held in private Supabase storage and is accessible to the account owner and, once linked to a client record, the assigned agent through temporary links. Audio playback access expires after 30 days. Permanent deletion is handled by review or on request; it is not currently automatic.",
  "مشاركة الاسم ورقم التواصل اختيارية، ولا تعني الموافقة على رسائل تسويقية. لا تشارك بيانات بطاقات الدفع أو كلمات المرور في المحادثة. يمكنك طلب توضيح بشأن بياناتك أو تصحيحها أو حذفها عبر":"Sharing your name and number is optional and is not consent to marketing. Do not share card details or passwords. To ask about, correct or delete your data, contact",
  "التواصل مع Tycoons":"Tycoons",
  "© ٢٠٢٦ تايكونز للاستثمار — كل الحقوق محفوظة":"© 2026 Tycoons Investments — All rights reserved",
  "شاليه في الساحل تحت 20 مليون":"North Coast chalet under EGP 20 million",
  "آي فيلا في التجمع 3 غرف":"3-bedroom iVilla in New Cairo",
  "شقة تحت 7 مليون":"Apartment under EGP 7 million",
  "استلام فوري متشطب":"Ready-to-move, fully finished",
  "وحدة متاحة":"Available homes",
  "مشروع":"Projects",
  "مطوّر":"Developers",
  "منطقة وموقع":"Areas and locations",
  "فيلا فاخرة على الساحل الشمالي":"A luxury villa on the North Coast",
  "بحث عقاري بالذكاء الاصطناعي":"AI-powered property search",
  "ابحث بصوتك بأي حاجة تيجي في بالك،":"Tell us what you have in mind.",
  "وإحنا نوصّلك للعقار المناسب.":"Find the property that fits.",
  "اكتب أو اتكلم بطريقتك — «عايز شاليه في الساحل تحت 20 مليون» — وشوف الوحدات المطابقة والبدائل القريبة من المخزون المحدث.":"Type or speak naturally — ‘a North Coast chalet under EGP 20 million’ — and explore matches and close alternatives from updated inventory.",
  "هتنتقل لصفحة نتائج كاملة تعرض المشاريع المطابقة والبدائل والفروق عن طلبك.":"Explore a full results page with matching projects, alternatives and how they differ from your request.",
  "جرّب:":"Try:",
  "الرئيسية":"Home",
  "المطورون":"Developers",
  "اختيار اللغة":"Choose language",
  "عربي":"العربية",
  "تواصل معنا على واتساب":"Contact us on WhatsApp",
  "واتساب":"WhatsApp",
  "مباشر":"LIVE",
  "بتتطرح دلوقتي":"Discover current launches",
  "أول فرصة لمشاريع لسه نازلة — من المطوّرين مباشرة، قبل السوق كله.":"Explore new project launches directly from developers.",
  "اسحب أو استخدم الأسهم":"Swipe or use the arrows",
  "السابق":"Previous",
  "التالي":"Next",
  "جديد":"New",
  "متاح":"Available",
  "يبدأ من":"Starting from",
  "غرف":"Bedrooms",
  "المساحة":"Area",
  "الاستلام":"Delivery",
  "تفاصيل المشروع":"Project details",
  "الساحل الشمالي":"North Coast",
  "شوف المتاح المحدث":"Explore current availability",
  "التجمع / القاهرة الجديدة":"New Cairo",
  "الشيخ زايد":"Sheikh Zayed",
  "العين السخنة":"Ain Sokhna",
  "العاصمة الإدارية":"New Capital",
  "استكشف بالمنطقة":"Explore by area",
  "مناطق مميّزة":"Find your location",
  "اختار منطقة والمساعد يبدأ البحث فيها فورًا.":"Choose an area to explore the properties available there.",
  "موثّق من المطوّر":"Verified developer-direct inventory",
  "كل وحدة مباشرة من الشركة المطوّرة — مفيش إعلانات مكررة ولا أسعار وهمية.":"Properties sourced directly from developers, without duplicate listings or misleading prices.",
  "أقساط تناسبك":"Payments that work for you",
  "خطط سداد لحد ١٠ سنين، وحاسبة قسط شفافة على كل مشروع.":"Payment plans up to 10 years and a transparent property payment calculator.",
  "رد فوري على واتساب":"Connect on WhatsApp",
  "المساعد بيكمّل معاك على واتساب بتفاصيل الوحدة اللي عايزها.":"Continue your enquiry on WhatsApp for details of the property you want.",
  "بنوصل المساعد الصوتي...":"Connecting the voice assistant…",
  "المساعد بيرد عليك...":"The assistant is speaking…",
  "بنسمعك... اتكلم دلوقتي":"Listening — speak now",
  "البحث في الوحدات العقارية المتاحة":"Search available properties",
  "اكتب طلبك: نوع الوحدة والمنطقة والميزانية":"Describe your property type, area and budget",
  "مثال: شقة في التجمع تحت 10 مليون ومقدم 5%":"Try: New Cairo apartment under EGP 10 million, 5% down",
  "مسح البحث":"Clear search",
  "بحث صوتي":"Voice search",
  "اعرض نتائج البحث":"Show search results",
  "اعرض النتائج":"View results",
  "فيلا":"Villa", "تاون هاوس":"Townhouse", "شاليه":"Chalet", "شقة":"Apartment", "بنتهاوس":"Penthouse", "سنة واحدة":"1 year", "سنتين":"2 years", "استلام فوري":"Ready to move", "٣ سنين":"3 years"
};
export function tr(text: string): string {
  if (!isEnglish()) return text;
  const key=text.replace(/\s+/g," ").trim();
  return copy[key] ?? text.replace(/[٠-٩]/g,c=>String(c.charCodeAt(0)-1632)).replace(/مليون جنيه/g,"million EGP").replace(/ج\.م/g,"EGP").replace(/م²/g,"m²").replace(/سنين/g,"years");
}
export function localeHref(path:string):string {
  if (!isEnglish()) return path;
  if(path==="/ar/"||path.startsWith("/ar/#"))return path.replace("/ar/","/en/directory/");
  return path.replace(/^\/ar\//,"/en/");
}
