const API_URL = "/api/admin-inventory";
let adminPassword = localStorage.getItem("tycoons_admin_password") || "";
let projects = [];
let units = [];
const loginPanel = document.getElementById("loginPanel");
const adminPanel = document.getElementById("adminPanel");
const adminPasswordInput = document.getElementById("adminPassword");
const loginBtn = document.getElementById("loginBtn");
const loginStatus = document.getElementById("loginStatus");
const projectForm = document.getElementById("projectForm");
const unitForm = document.getElementById("unitForm");
const projectSelect = document.getElementById("projectSelect");
const unitTableWrap = document.getElementById("unitTableWrap");
const unitFilter = document.getElementById("unitFilter");
const refreshBtn = document.getElementById("refreshBtn");
const resetProjectBtn = document.getElementById("resetProjectBtn");
const resetUnitBtn = document.getElementById("resetUnitBtn");
const csvFile = document.getElementById("csvFile");
const importCsvBtn = document.getElementById("importCsvBtn");
const importStatus = document.getElementById("importStatus");
function setStatus(el,text,type=""){el.className="status "+type;el.classList.remove("hidden");el.textContent=text;}
function money(v){if(!v)return"-";return new Intl.NumberFormat("en-US").format(Number(v));}
function formData(form){return Object.fromEntries(new FormData(form).entries());}
function cleanNumber(v){if(v===""||v===null||v===undefined)return null;const n=Number(String(v).replace(/,/g,""));return Number.isFinite(n)?n:null;}
async function api(action,payload={}){const res=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"application/json","X-Admin-Password":adminPassword},body:JSON.stringify({action,...payload})});const text=await res.text();let data;try{data=JSON.parse(text)}catch{data={error:text}}if(!res.ok)throw new Error(data.error||"Admin request failed");return data;}
async function login(){adminPassword=adminPasswordInput.value.trim();if(!adminPassword){setStatus(loginStatus,"Enter admin password first.","error");return}try{loginBtn.disabled=true;await loadData();localStorage.setItem("tycoons_admin_password",adminPassword);loginPanel.classList.add("hidden");adminPanel.classList.remove("hidden");}catch(e){setStatus(loginStatus,e.message,"error")}finally{loginBtn.disabled=false;}}
async function loadData(){const data=await api("list");projects=data.projects||[];units=data.units||[];renderStats();renderProjectOptions();renderUnits();}
function renderStats(){document.getElementById("projectCount").textContent=projects.length;document.getElementById("unitCount").textContent=units.length;document.getElementById("availableCount").textContent=units.filter(u=>u.availability_status==="available").length;}
function renderProjectOptions(){projectSelect.innerHTML='<option value="">Choose project</option>'+projects.map(p=>`<option value="${p.id}">${p.name} — ${p.location||""}</option>`).join("");}
function filteredUnits(){const q=unitFilter.value.trim().toLowerCase();if(!q)return units;return units.filter(u=>[u.project_name,u.developer,u.location,u.unit_type,u.bedrooms_text,u.starting_price,u.down_payment_text,u.installments_text,u.delivery_text,u.availability_status].join(" ").toLowerCase().includes(q));}
function renderUnits(){const list=filteredUnits();unitTableWrap.innerHTML=`<table><thead><tr><th>Project</th><th>Unit</th><th>Price</th><th>Payment</th><th>Delivery</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>${list.map(unit=>`<tr><td><strong>${unit.project_name||"-"}</strong><br><span class="pill">${unit.location||"-"}</span></td><td>${unit.unit_type||"-"}<br><span class="pill">${unit.bedrooms_text||"No bedrooms"}</span></td><td>${money(unit.starting_price)} EGP</td><td>${unit.down_payment_text||"-"}<br>${unit.installments_text||""}</td><td>${unit.delivery_text||"-"}</td><td><span class="pill">${unit.availability_status||"-"}</span></td><td>${unit.last_updated_at?new Date(unit.last_updated_at).toLocaleDateString():"-"}</td><td><div class="actions"><button class="ghost small" type="button" onclick="editUnit('${unit.id}')">Edit</button><button class="ghost small" type="button" onclick="toggleUnit('${unit.id}', '${unit.availability_status==="available"?"unavailable":"available"}')">${unit.availability_status==="available"?"Mark unavailable":"Mark available"}</button></div></td></tr>`).join("")}</tbody></table>`;}
async function saveProject(event){event.preventDefault();const d=formData(projectForm);const project={id:d.id||undefined,name:d.name?.trim(),developer:d.developer?.trim()||null,location:d.location?.trim(),status:d.status?.trim()||null,min_price:cleanNumber(d.min_price),down_payment_text:d.down_payment_text?.trim()||null,installments_text:d.installments_text?.trim()||null,delivery_text:d.delivery_text?.trim()||null,description:d.description?.trim()||null};if(!project.name||!project.location){alert("Project name and location are required.");return}await api("saveProject",{project});projectForm.reset();await loadData();}
async function saveUnit(event){event.preventDefault();const d=formData(unitForm);const p=projects.find(x=>x.id===d.project_id);if(!p){alert("Choose a project first.");return}const unit={id:d.id||undefined,project_id:p.id,project_name:p.name,developer:p.developer||null,location:p.location,unit_type:d.unit_type?.trim(),bedrooms_text:d.bedrooms_text?.trim()||null,area_sqm:cleanNumber(d.area_sqm),starting_price:cleanNumber(d.starting_price),down_payment_text:d.down_payment_text?.trim()||null,installments_text:d.installments_text?.trim()||null,delivery_text:d.delivery_text?.trim()||null,finishing:d.finishing?.trim()||null,availability_status:d.availability_status||"available",description:d.description?.trim()||null};if(!unit.unit_type||!unit.starting_price){alert("Unit type and starting price are required.");return}await api("saveUnit",{unit});unitForm.reset();await loadData();}
window.editUnit=function(id){const unit=units.find(u=>u.id===id);if(!unit)return;unitForm.id.value=unit.id||"";unitForm.project_id.value=unit.project_id||"";unitForm.unit_type.value=unit.unit_type||"";unitForm.bedrooms_text.value=unit.bedrooms_text||"";unitForm.area_sqm.value=unit.area_sqm||"";unitForm.starting_price.value=unit.starting_price||"";unitForm.down_payment_text.value=unit.down_payment_text||"";unitForm.installments_text.value=unit.installments_text||"";unitForm.delivery_text.value=unit.delivery_text||"";unitForm.finishing.value=unit.finishing||"";unitForm.availability_status.value=unit.availability_status||"available";unitForm.description.value=unit.description||"";unitForm.scrollIntoView({behavior:"smooth",block:"start"});}
window.toggleUnit=async function(id,availability_status){await api("toggleUnit",{id,availability_status});await loadData();}
function parseCSV(text){const rows=[];let cur=[],val="",q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){val+='"';i++}else if(c==='"'){q=!q}else if(c===","&&!q){cur.push(val);val=""}else if((c==="\n"||c==="\r")&&!q){if(c==="\r"&&n==="\n")i++;cur.push(val);val="";if(cur.some(x=>x.trim()!==""))rows.push(cur);cur=[]}else{val+=c}}cur.push(val);if(cur.some(x=>x.trim()!==""))rows.push(cur);const headers=rows.shift().map(h=>h.trim());return rows.map(r=>{const o={};headers.forEach((h,i)=>o[h]=(r[i]||"").trim());return o});}
async function importCsv(){if(!csvFile.files?.[0]){setStatus(importStatus,"Choose a CSV file first.","error");return}try{importCsvBtn.disabled=true;const rows=parseCSV(await csvFile.files[0].text());if(!rows.length){setStatus(importStatus,"CSV has no rows.","error");return}const result=await api("importUnits",{rows});setStatus(importStatus,`Imported ${result.inserted_units} units and created ${result.created_projects} projects.`,"success");await loadData();}catch(e){setStatus(importStatus,e.message,"error")}finally{importCsvBtn.disabled=false;}}
loginBtn.addEventListener("click",login);adminPasswordInput.addEventListener("keydown",e=>{if(e.key==="Enter")login()});projectForm.addEventListener("submit",saveProject);unitForm.addEventListener("submit",saveUnit);refreshBtn.addEventListener("click",loadData);unitFilter.addEventListener("input",renderUnits);resetProjectBtn.addEventListener("click",()=>projectForm.reset());resetUnitBtn.addEventListener("click",()=>unitForm.reset());importCsvBtn.addEventListener("click",importCsv);if(adminPassword)adminPasswordInput.value=adminPassword;
