import { useEffect, useMemo, useState } from "react";
import { useParams } from "react-router";
import { salesWarRoomApi } from "../lib/salesWarRoomApi";

const stages = ["New Lead","Contacted","Warm","Hot / Very Potential","Meeting Scheduled","Meeting Held","Negotiation / Closing","Won","Lost / Dead"];
const ar: Record<string,string> = {
  "New Lead":"ليد جديد","Contacted":"تم التواصل","Warm":"Warm","Hot / Very Potential":"Hot / قوي جدًا","Meeting Scheduled":"ميعاد متحدد","Meeting Held":"تم الاجتماع","Negotiation / Closing":"تفاوض / Closing","Won":"مكسب","Lost / Dead":"خسارة / Dead"
};

export default function SalesWarRoom(){
  const { slug = "" } = useParams();
  const sessionKey=`warRoomAgentToken:${slug}`;
  const adminToken=localStorage.getItem("warRoomAdminToken")||"";
  const isAdminView=Boolean(adminToken);
  const [lang,setLang]=useState<"en"|"ar">((localStorage.getItem("warRoomLang") as "en"|"ar")||"en");
  const [token,setToken]=useState(()=>localStorage.getItem(sessionKey)||"");
  const [password,setPassword]=useState("");
  const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(Boolean(token||adminToken)); const [err,setErr]=useState("");
  const [lead,setLead]=useState({client_name:"",phone:"",budget:"",stage:"New Lead",next_action:"",next_action_trigger:"",notes:""});
  const t=(en:string,arr:string)=>lang==="ar"?arr:en;
  const clearSession=()=>{localStorage.removeItem(sessionKey);setToken("");setData(null)};
  const load=async()=>{if(!token){setLoading(false);return}try{setLoading(true);setData(await salesWarRoomApi.getAgent(slug,token));setErr("")}catch(e:any){if(e.message==="unauthorized"){clearSession();setErr(t("Session expired. Enter your password again.","انتهت جلسة الدخول. اكتب الباسورد مرة تانية."))}else setErr(e.message)}finally{setLoading(false)}};
  async function bootstrapAdminAccess(){if(token||!adminToken)return;try{setLoading(true);setErr("");const r=await salesWarRoomApi.adminAgentAccess(adminToken,slug);localStorage.setItem(sessionKey,r.token);setToken(r.token)}catch(e:any){if(e.message==="unauthorized")localStorage.removeItem("warRoomAdminToken");setErr(e.message==="unauthorized"?t("Admin session expired. Sign in again from Admin.","جلسة الأدمن انتهت. ادخل من صفحة الأدمن مرة تانية."):e.message)}finally{setLoading(false)}}
  async function login(){try{setLoading(true);setErr("");const r=await salesWarRoomApi.agentLogin(slug,password);localStorage.setItem(sessionKey,r.token);setToken(r.token);setPassword("")}catch(e:any){setErr(e.message==="invalid_credentials"?t("Wrong password","الباسورد غير صحيح"):e.message)}finally{setLoading(false)}}
  useEffect(()=>{document.title="Sales War Room"; const m=document.createElement("meta");m.name="robots";m.content="noindex,nofollow,noarchive";document.head.appendChild(m);return()=>m.remove()},[]);
  useEffect(()=>{if(token)load();else if(adminToken)bootstrapAdminAccess();else setLoading(false)},[slug,token]);
  useEffect(()=>{localStorage.setItem("warRoomLang",lang);document.documentElement.dir=lang==="ar"?"rtl":"ltr"},[lang]);

  if(!token&&adminToken&&loading)return <main className="grid min-h-screen place-items-center bg-slate-950 text-white">{t("Opening agent dashboard as Admin…","جاري فتح داشبورد الـAgent كـAdmin…")}</main>;
  if(!token)return <main className="grid min-h-screen place-items-center bg-slate-950 p-4 text-white" dir={lang==="ar"?"rtl":"ltr"}><div className="w-full max-w-sm rounded-3xl border border-white/10 bg-white/5 p-6 shadow-2xl"><div className="mb-6 flex items-center justify-between"><div><div className="text-xs font-black tracking-[.18em] text-slate-400">TYCOONS SALES WAR ROOM</div><h1 className="mt-1 text-2xl font-black">{t("Agent Access","دخول الـAgent")}</h1></div><button onClick={()=>setLang(lang==="ar"?"en":"ar")} className="rounded-full border border-white/20 px-3 py-2 text-xs font-black">{lang==="ar"?"EN":"عربي"}</button></div><p className="mb-4 text-sm text-slate-400">{t("Enter your personal password to open your scoreboard.","اكتب الباسورد الخاص بيك علشان تفتح الـScoreboard.")}</p><input type="password" autoFocus value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==="Enter"&&login()} placeholder={t("Password","الباسورد")} className="w-full rounded-xl border border-white/10 bg-white/10 p-3 outline-none"/><button disabled={loading||!password} onClick={login} className="mt-3 w-full rounded-xl bg-white p-3 font-black text-slate-950 disabled:opacity-50">{loading?t("Checking…","جاري التحقق…"):t("Open War Room","افتح غرفة العمليات")}</button>{err&&<div className="mt-3 text-sm text-red-300">{err}</div>}</div></main>;

  const score=data?.score||{}; const pipeline=data?.pipeline||[];
  const matches=[1,2,3,4].map(i=>({i,calls:Number(score[`match${i}_calls`]||0),status:score[`match${i}_status`]||"open"}));
  const todayWins=matches.filter(m=>m.status==="win").length, todayLosses=matches.filter(m=>m.status==="loss").length, todayCalls=matches.reduce((a,m)=>a+m.calls,0);
  const warm=pipeline.filter((l:any)=>l.stage==="Warm").length, hot=pipeline.filter((l:any)=>l.stage==="Hot / Very Potential").length;
  const weekly=useMemo(()=>{const rows=data?.weekScores||[];let wins=0,losses=0,calls=0,potential=0,meetings=0,sales=0;rows.forEach((r:any)=>{for(let i=1;i<=4;i++){calls+=Number(r[`match${i}_calls`]||0);if(r[`match${i}_status`]==="win")wins++;if(r[`match${i}_status`]==="loss")losses++}potential+=Number(r.potential_cases||0);meetings+=Number(r.meetings_scheduled||0);sales+=Number(r.sales_volume||0)});return{wins,losses,calls,potential,meetings,sales,total:wins+losses}},[data]);
  async function changeCalls(i:number,delta:number){const m=matches[i-1];if(m.status!=="open")return;for(let x=1;x<i;x++)if(matches[x-1].status==="open"){alert(t(`Finish Match ${x} first.`,`اقفل Match ${x} الأول.`));return}const calls=Math.max(0,Math.min(50,m.calls+delta));const body:any={slug,[`match${i}_calls`]:calls};if(calls===50)body[`match${i}_status`]="win";await salesWarRoomApi.patchScore(token,body);load()}
  async function finish(i:number){const m=matches[i-1];if(m.status!=="open")return;if(m.calls<50&&!confirm(t(`Record Match ${i} as LOSS at ${m.calls}/50?`,`نسجل Match ${i} خسارة عند ${m.calls}/50؟`)))return;await salesWarRoomApi.patchScore(token,{slug,[`match${i}_calls`]:m.calls,[`match${i}_status`]:m.calls===50?"win":"loss"});load()}
  async function potential(d:number){await salesWarRoomApi.patchScore(token,{slug,potential_cases:Math.max(0,Number(score.potential_cases||0)+d)});load()}
  async function addLead(){if(!lead.client_name.trim())return alert(t("Client name required","اسم العميل مطلوب"));if(lead.stage==="Warm"&&(!lead.next_action.trim()||!lead.next_action_trigger.trim()))return alert(t("Warm requires Next Action + Date/Trigger","Warm لازم يكون له Next Action + تاريخ/Trigger"));await salesWarRoomApi.addLead(token,{slug,...lead});setLead({client_name:"",phone:"",budget:"",stage:"New Lead",next_action:"",next_action_trigger:"",notes:""});load()}
  async function moveLead(id:string,stage:string){const x=pipeline.find((p:any)=>p.id===id);if(stage==="Warm"&&(!x.next_action||!x.next_action_trigger)){alert(t("Add Next Action + Date/Trigger before Warm","ضيف Next Action + Date/Trigger قبل ما يبقى Warm"));return}await salesWarRoomApi.updateLead(token,{id,stage});load()}
  if(loading&&!data)return <main className="grid min-h-screen place-items-center bg-slate-950 text-white">{t("Loading War Room…","جاري تحميل غرفة العمليات…")}</main>;
  if(err&&!data)return <main className="grid min-h-screen place-items-center bg-slate-950 p-4 text-white"><div className="text-center"><div>{t("Dashboard unavailable","الداشبورد غير متاحة")}</div><div className="mt-2 text-sm text-red-300">{err}</div><button onClick={clearSession} className="mt-4 rounded-xl bg-white px-4 py-2 font-black text-slate-950">{t("Sign in again","دخول من جديد")}</button></div></main>;
  const name=lang==="ar"?data.agent.name_ar:data.agent.name_en;
  return <main className="min-h-screen bg-[#f3f5f7] text-[#111317]" dir={lang==="ar"?"rtl":"ltr"}>
    <div className="mx-auto max-w-[1600px] p-3 md:p-5">
      <header className="mb-4 flex items-center justify-between"><div><div className="text-xs font-black tracking-[.2em] text-slate-500">TYCOONS SALES WAR ROOM</div><h1 className="text-2xl font-black">{name}</h1></div><div className="flex gap-2"><button onClick={()=>setLang(lang==="ar"?"en":"ar")} className="rounded-full border bg-white px-4 py-2 text-sm font-black shadow-sm">{lang==="ar"?"EN":"عربي"}</button>{isAdminView?<button onClick={()=>window.location.href="/sales-war-room/admin"} className="rounded-full bg-slate-950 px-4 py-2 text-sm font-black text-white">{t("Back to Admin","الرجوع للأدمن")}</button>:<button onClick={clearSession} className="rounded-full bg-slate-950 px-4 py-2 text-sm font-black text-white">{t("Logout","خروج")}</button>}</div></header>
      <section className="grid gap-4 rounded-3xl bg-slate-950 p-4 text-white shadow-xl md:grid-cols-[1.15fr_1fr] md:p-6">
        <div className="flex flex-col justify-between gap-6"><div><div className="text-xs font-black tracking-[.18em] text-slate-400">{t("TODAY · WHAT DO I NEED TO WIN NEXT?","اليوم · إيه اللي ناقصني علشان أكسب الـMatch الجاي؟")}</div><div className="mt-4 flex flex-wrap items-end gap-8"><div><div className="text-xs text-slate-400">{t("CALL TARGET","هدف المكالمات")}</div><div className="text-5xl font-black">{todayCalls}<span className="text-2xl text-slate-500">/200</span></div></div><div><div className="text-xs text-slate-400">{t("TODAY'S RECORD","نتيجة اليوم")}</div><div className="text-4xl font-black"><span className="text-emerald-400">{todayWins}W</span> – <span className="text-rose-400">{todayLosses}L</span></div></div></div></div><div className="rounded-2xl border border-white/10 bg-white/5 p-3 text-sm font-bold">{t("No carryover. Every Match starts 0–0.","مفيش تعويض. كل Match بيبدأ 0–0.")}</div></div>
        <div className="grid grid-cols-2 gap-2">{matches.map(m=><div key={m.i} className="rounded-2xl bg-white p-3 text-slate-950"><div className="flex items-center justify-between text-xs font-black"><span>MATCH {m.i}</span><span className={`rounded-full px-2 py-1 ${m.status==="win"?"bg-emerald-100 text-emerald-700":m.status==="loss"?"bg-rose-100 text-rose-700":"bg-slate-100"}`}>{m.status==="open"?t("LIVE","شغال"):m.status.toUpperCase()}</span></div><div className="mt-2 text-3xl font-black">{m.calls}<span className="text-sm text-slate-400"> / 50</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-slate-950" style={{width:`${m.calls*2}%`}}/></div><div className="mt-3 grid grid-cols-3 gap-1"><button onClick={()=>changeCalls(m.i,5)} className="rounded-lg border px-2 py-2 text-xs font-black">+5</button><button onClick={()=>changeCalls(m.i,25)} className="rounded-lg border px-2 py-2 text-xs font-black">+25</button><button onClick={()=>finish(m.i)} className="rounded-lg bg-slate-950 px-2 py-2 text-xs font-black text-white">{t("Finish","اقفل")}</button></div></div>)}</div>
      </section>
      <section className="mt-4 grid gap-3 md:grid-cols-4"><Kpi title={t("Warm Pipeline","Warm Pipeline")} value={`${warm} / 10`} sub={warm<10?t("RED ALERT","إنذار أحمر"):t("Protected","آمن")} danger={warm<10}/><Kpi title={t("Potential Today","Potential النهاردة")} value={`${score.potential_cases||0} / ~5`} actions={<><button onClick={()=>potential(1)} className="rounded-lg border px-2 py-1">+1</button><button onClick={()=>potential(-1)} className="rounded-lg border px-2 py-1">−1</button></>}/><Kpi title={t("Weekly Meetings","Meetings الأسبوع")} value={`${weekly.meetings} / 8`} sub={`${t("Hot","Hot")}: ${hot}`}/><Kpi title={t("Weekly Match Score","نتيجة الأسبوع")} value={`${weekly.wins}W / ${weekly.total}`} sub={`${weekly.total?Math.round(weekly.wins/weekly.total*100):0}% ${t("win rate","نسبة فوز")}`}/></section>
      {warm<10&&<div className="mt-3 rounded-2xl border-2 border-red-500 bg-red-50 p-4 text-red-800"><b>🚨 {t("PIPELINE RED ALERT","إنذار أحمر للـPIPELINE")}</b><div className="mt-1 text-sm">{t("Warm is below 10. Pipeline generation outranks side projects.","الـWarm أقل من 10. بناء الـPipeline له الأولوية قبل أي Side Projects.")}</div></div>}
      <section className="mt-4 rounded-3xl border bg-white p-4 shadow-sm"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-lg font-black">{t("Pipeline Kanban","Pipeline Kanban")}</h2><p className="text-xs text-slate-500">{t("Warm requires an agreed next step and trigger.","Warm لازم يكون فيه Next Step متفق عليه + Trigger/Date.")}</p></div></div><div className="overflow-x-auto pb-2"><div className="grid min-w-max grid-flow-col auto-cols-[250px] gap-2">{stages.map(stage=><div key={stage} className="min-h-[300px] rounded-2xl border bg-slate-50 p-2"><div className="mb-2 flex items-center justify-between text-xs font-black"><span>{lang==="ar"?ar[stage]:stage}</span><span className="rounded-full bg-white px-2 py-1">{pipeline.filter((x:any)=>x.stage===stage).length}</span></div>{pipeline.filter((x:any)=>x.stage===stage).map((x:any)=><div key={x.id} className={`mb-2 rounded-xl border bg-white p-3 shadow-sm ${stage==="Hot / Very Potential"?"border-red-300":stage==="Warm"?"border-amber-300":""}`}><div className="font-black">{x.client_name}</div><div className="mt-1 text-xs text-slate-500">{x.budget||x.phone}</div>{(x.next_action||x.next_action_trigger)&&<div className="mt-2 rounded-lg bg-slate-50 p-2 text-xs"><b>{t("Next","التالي")}: </b>{x.next_action}<br/>{x.next_action_trigger}</div>}<select value={x.stage} onChange={e=>moveLead(x.id,e.target.value)} className="mt-2 w-full rounded-lg border p-2 text-xs font-bold">{stages.map(s=><option key={s} value={s}>{lang==="ar"?ar[s]:s}</option>)}</select></div>)}</div>)}</div></div>
        <div className="mt-5 border-t pt-4"><h3 className="mb-3 font-black">+ {t("Add Lead","إضافة Lead")}</h3><div className="grid gap-2 md:grid-cols-4"><input value={lead.client_name} onChange={e=>setLead({...lead,client_name:e.target.value})} placeholder={t("Client name","اسم العميل")} className="rounded-xl border p-3"/><input value={lead.phone} onChange={e=>setLead({...lead,phone:e.target.value})} placeholder={t("Phone","الموبايل")} className="rounded-xl border p-3"/><input value={lead.budget} onChange={e=>setLead({...lead,budget:e.target.value})} placeholder={t("Budget","الميزانية")} className="rounded-xl border p-3"/><select value={lead.stage} onChange={e=>setLead({...lead,stage:e.target.value})} className="rounded-xl border p-3">{stages.map(s=><option key={s} value={s}>{lang==="ar"?ar[s]:s}</option>)}</select><input value={lead.next_action} onChange={e=>setLead({...lead,next_action:e.target.value})} placeholder={t("Next action","الخطوة الجاية")} className="rounded-xl border p-3 md:col-span-2"/><input value={lead.next_action_trigger} onChange={e=>setLead({...lead,next_action_trigger:e.target.value})} placeholder={t("Date / trigger","التاريخ / Trigger")} className="rounded-xl border p-3 md:col-span-2"/><input value={lead.notes} onChange={e=>setLead({...lead,notes:e.target.value})} placeholder={t("Competitive notes / context","ملاحظات / منافسين")} className="rounded-xl border p-3 md:col-span-3"/><button onClick={addLead} className="rounded-xl bg-slate-950 p-3 font-black text-white">{t("Add to Pipeline","ضيف للـPipeline")}</button></div></div>
      </section>
      <section className="mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-3xl border bg-white p-4"><h2 className="font-black">{t("Weekly Review","مراجعة الأسبوع")}</h2><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><Metric label={t("Calls","Calls")} value={weekly.calls}/><Metric label={t("Potential","Potential")} value={weekly.potential}/><Metric label={t("Wins","Wins")} value={weekly.wins}/><Metric label={t("Losses","Losses")} value={weekly.losses}/><Metric label={t("Meetings","Meetings")} value={weekly.meetings}/><Metric label={t("Sales","Sales")} value={`EGP ${Number(weekly.sales).toLocaleString()}`}/></div></div><div className="rounded-3xl border bg-white p-4"><h2 className="font-black">{t("Operating Rules","قواعد التشغيل")}</h2><ol className="mt-3 space-y-2 text-sm text-slate-700"><li><b>1.</b> {t("No Carryover","مفيش تعويض")}</li><li><b>2.</b> {t("Every Match Starts 0–0","كل Match بيبدأ 0–0")}</li><li><b>3.</b> {t("Warm Pipeline Must Stay Above 10","Warm Pipeline لازم يفضل فوق 10")}</li><li><b>4.</b> {t("Hot Cases Do Not Stop Pipeline Building","Hot Cases ما توقفش بناء Pipeline")}</li><li><b>5.</b> {t("First Priority = Pipeline","الأولوية الأولى = Pipeline")}</li></ol></div></section>
    </div>
  </main>
}
function Kpi({title,value,sub,actions,danger=false}:any){return <div className={`rounded-2xl border bg-white p-4 shadow-sm ${danger?"border-red-400":""}`}><div className="text-xs font-black text-slate-500">{title}</div><div className={`mt-1 text-3xl font-black ${danger?"text-red-600":""}`}>{value}</div>{sub&&<div className="mt-1 text-xs font-bold text-slate-500">{sub}</div>}{actions&&<div className="mt-3 flex gap-2 text-xs">{actions}</div>}</div>}
function Metric({label,value}:any){return <div className="rounded-xl bg-slate-50 p-3"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 font-black">{value}</div></div>}
